language: python
python:
    - "3.8"

install:
    - pip install -r requirements.txt

script:
    - python publish.py
after_script:
    - cp dist out/
deploy:
    provider: pages
    local_dir: out
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
        branch: master_demo